# Generated by Django 2.2.5 on 2019-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_state', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age_16_18', models.IntegerField()),
                ('age_18_30', models.IntegerField()),
                ('age_30_50', models.IntegerField()),
                ('age_50_above', models.IntegerField()),
            ],
        ),
    ]
