# Generated by Django 2.2.5 on 2019-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodofsentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_state', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('sentence_period', models.CharField(max_length=100)),
                ('age_16_18', models.IntegerField()),
                ('age_18_30', models.IntegerField()),
                ('age_30_50', models.IntegerField()),
                ('age_50_above', models.IntegerField()),
            ],
        ),
    ]
