# Generated by Django 2.2.5 on 2019-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_periodofsentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_state', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
