# Generated by Django 2.2.5 on 2019-09-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('Activity', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
