# Generated by Django 2.2.5 on 2019-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_goods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='escapes',
        ),
        migrations.RenameField(
            model_name='escapes',
            old_name='value',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='escapes',
            name='Activity',
        ),
        migrations.AddField(
            model_name='escapes',
            name='detail',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
