# Generated by Django 2.2.5 on 2019-09-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190929_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='escapes',
        ),
    ]
