# Generated by Django 2.2.5 on 2019-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_escapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='escapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('detail', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
